/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ShoppingListIndexImport } from './routes/shopping-list/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as RecipesIndexImport } from './routes/recipes/index'
import { Route as NutrientsIndexImport } from './routes/nutrients/index'
import { Route as IngredientsIndexImport } from './routes/ingredients/index'
import { Route as FoodLogIndexImport } from './routes/food-log/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as ConsumptionIndexImport } from './routes/consumption/index'
import { Route as ShoppingListNewImport } from './routes/shopping-list/new'
import { Route as ShoppingListItemIdImport } from './routes/shopping-list/$itemId'
import { Route as RecipesNewRecipeImport } from './routes/recipes/new-recipe'
import { Route as RecipesRecipeIdImport } from './routes/recipes/$recipeId'
import { Route as NutrientsNewImport } from './routes/nutrients/new'
import { Route as NutrientslayoutImport } from './routes/nutrients/__layout'
import { Route as NutrientsNutrientIdImport } from './routes/nutrients/$nutrientId'
import { Route as IngredientsNewImport } from './routes/ingredients/new'
import { Route as IngredientslayoutImport } from './routes/ingredients/__layout'
import { Route as IngredientsIngredientIdImport } from './routes/ingredients/$ingredientId'
import { Route as FoodLoglayoutImport } from './routes/food-log/__layout'
import { Route as FoodLogDateImport } from './routes/food-log/$date'
import { Route as RecipesRecipeIdEditImport } from './routes/recipes/$recipeId.edit'
import { Route as NutrientsNutrientIdEditImport } from './routes/nutrients/$nutrientId.edit'
import { Route as IngredientsIngredientIdEditImport } from './routes/ingredients/$ingredientId.edit'
import { Route as FoodLogMealMealIdImport } from './routes/food-log/meal/$mealId'

// Create Virtual Routes

const NutrientsImport = createFileRoute('/nutrients')()
const IngredientsImport = createFileRoute('/ingredients')()
const FoodLogImport = createFileRoute('/food-log')()

// Create/Update Routes

const NutrientsRoute = NutrientsImport.update({
  id: '/nutrients',
  path: '/nutrients',
  getParentRoute: () => rootRoute,
} as any)

const IngredientsRoute = IngredientsImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRoute,
} as any)

const FoodLogRoute = FoodLogImport.update({
  id: '/food-log',
  path: '/food-log',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ShoppingListIndexRoute = ShoppingListIndexImport.update({
  id: '/shopping-list/',
  path: '/shopping-list/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesIndexRoute = RecipesIndexImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRoute,
} as any)

const NutrientsIndexRoute = NutrientsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NutrientsRoute,
} as any)

const IngredientsIndexRoute = IngredientsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IngredientsRoute,
} as any)

const FoodLogIndexRoute = FoodLogIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FoodLogRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const ConsumptionIndexRoute = ConsumptionIndexImport.update({
  id: '/consumption/',
  path: '/consumption/',
  getParentRoute: () => rootRoute,
} as any)

const ShoppingListNewRoute = ShoppingListNewImport.update({
  id: '/shopping-list/new',
  path: '/shopping-list/new',
  getParentRoute: () => rootRoute,
} as any)

const ShoppingListItemIdRoute = ShoppingListItemIdImport.update({
  id: '/shopping-list/$itemId',
  path: '/shopping-list/$itemId',
  getParentRoute: () => rootRoute,
} as any)

const RecipesNewRecipeRoute = RecipesNewRecipeImport.update({
  id: '/recipes/new-recipe',
  path: '/recipes/new-recipe',
  getParentRoute: () => rootRoute,
} as any)

const RecipesRecipeIdRoute = RecipesRecipeIdImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRoute,
} as any)

const NutrientsNewRoute = NutrientsNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => NutrientsRoute,
} as any)

const NutrientslayoutRoute = NutrientslayoutImport.update({
  id: '/__layout',
  getParentRoute: () => NutrientsRoute,
} as any)

const NutrientsNutrientIdRoute = NutrientsNutrientIdImport.update({
  id: '/nutrients/$nutrientId',
  path: '/nutrients/$nutrientId',
  getParentRoute: () => rootRoute,
} as any)

const IngredientsNewRoute = IngredientsNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => IngredientsRoute,
} as any)

const IngredientslayoutRoute = IngredientslayoutImport.update({
  id: '/__layout',
  getParentRoute: () => IngredientsRoute,
} as any)

const IngredientsIngredientIdRoute = IngredientsIngredientIdImport.update({
  id: '/ingredients/$ingredientId',
  path: '/ingredients/$ingredientId',
  getParentRoute: () => rootRoute,
} as any)

const FoodLoglayoutRoute = FoodLoglayoutImport.update({
  id: '/__layout',
  getParentRoute: () => FoodLogRoute,
} as any)

const FoodLogDateRoute = FoodLogDateImport.update({
  id: '/food-log/$date',
  path: '/food-log/$date',
  getParentRoute: () => rootRoute,
} as any)

const RecipesRecipeIdEditRoute = RecipesRecipeIdEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RecipesRecipeIdRoute,
} as any)

const NutrientsNutrientIdEditRoute = NutrientsNutrientIdEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => NutrientsNutrientIdRoute,
} as any)

const IngredientsIngredientIdEditRoute =
  IngredientsIngredientIdEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => IngredientsIngredientIdRoute,
  } as any)

const FoodLogMealMealIdRoute = FoodLogMealMealIdImport.update({
  id: '/meal/$mealId',
  path: '/meal/$mealId',
  getParentRoute: () => FoodLogRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/food-log/$date': {
      id: '/food-log/$date'
      path: '/food-log/$date'
      fullPath: '/food-log/$date'
      preLoaderRoute: typeof FoodLogDateImport
      parentRoute: typeof rootRoute
    }
    '/food-log': {
      id: '/food-log'
      path: '/food-log'
      fullPath: '/food-log'
      preLoaderRoute: typeof FoodLogImport
      parentRoute: typeof rootRoute
    }
    '/food-log/__layout': {
      id: '/food-log/__layout'
      path: '/food-log'
      fullPath: '/food-log'
      preLoaderRoute: typeof FoodLoglayoutImport
      parentRoute: typeof FoodLogRoute
    }
    '/ingredients/$ingredientId': {
      id: '/ingredients/$ingredientId'
      path: '/ingredients/$ingredientId'
      fullPath: '/ingredients/$ingredientId'
      preLoaderRoute: typeof IngredientsIngredientIdImport
      parentRoute: typeof rootRoute
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsImport
      parentRoute: typeof rootRoute
    }
    '/ingredients/__layout': {
      id: '/ingredients/__layout'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientslayoutImport
      parentRoute: typeof IngredientsRoute
    }
    '/ingredients/new': {
      id: '/ingredients/new'
      path: '/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof IngredientsNewImport
      parentRoute: typeof IngredientsImport
    }
    '/nutrients/$nutrientId': {
      id: '/nutrients/$nutrientId'
      path: '/nutrients/$nutrientId'
      fullPath: '/nutrients/$nutrientId'
      preLoaderRoute: typeof NutrientsNutrientIdImport
      parentRoute: typeof rootRoute
    }
    '/nutrients': {
      id: '/nutrients'
      path: '/nutrients'
      fullPath: '/nutrients'
      preLoaderRoute: typeof NutrientsImport
      parentRoute: typeof rootRoute
    }
    '/nutrients/__layout': {
      id: '/nutrients/__layout'
      path: '/nutrients'
      fullPath: '/nutrients'
      preLoaderRoute: typeof NutrientslayoutImport
      parentRoute: typeof NutrientsRoute
    }
    '/nutrients/new': {
      id: '/nutrients/new'
      path: '/new'
      fullPath: '/nutrients/new'
      preLoaderRoute: typeof NutrientsNewImport
      parentRoute: typeof NutrientsImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdImport
      parentRoute: typeof rootRoute
    }
    '/recipes/new-recipe': {
      id: '/recipes/new-recipe'
      path: '/recipes/new-recipe'
      fullPath: '/recipes/new-recipe'
      preLoaderRoute: typeof RecipesNewRecipeImport
      parentRoute: typeof rootRoute
    }
    '/shopping-list/$itemId': {
      id: '/shopping-list/$itemId'
      path: '/shopping-list/$itemId'
      fullPath: '/shopping-list/$itemId'
      preLoaderRoute: typeof ShoppingListItemIdImport
      parentRoute: typeof rootRoute
    }
    '/shopping-list/new': {
      id: '/shopping-list/new'
      path: '/shopping-list/new'
      fullPath: '/shopping-list/new'
      preLoaderRoute: typeof ShoppingListNewImport
      parentRoute: typeof rootRoute
    }
    '/consumption/': {
      id: '/consumption/'
      path: '/consumption'
      fullPath: '/consumption'
      preLoaderRoute: typeof ConsumptionIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/food-log/': {
      id: '/food-log/'
      path: '/'
      fullPath: '/food-log/'
      preLoaderRoute: typeof FoodLogIndexImport
      parentRoute: typeof FoodLogImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexImport
      parentRoute: typeof IngredientsImport
    }
    '/nutrients/': {
      id: '/nutrients/'
      path: '/'
      fullPath: '/nutrients/'
      preLoaderRoute: typeof NutrientsIndexImport
      parentRoute: typeof NutrientsImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/shopping-list/': {
      id: '/shopping-list/'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListIndexImport
      parentRoute: typeof rootRoute
    }
    '/food-log/meal/$mealId': {
      id: '/food-log/meal/$mealId'
      path: '/meal/$mealId'
      fullPath: '/food-log/meal/$mealId'
      preLoaderRoute: typeof FoodLogMealMealIdImport
      parentRoute: typeof FoodLogImport
    }
    '/ingredients/$ingredientId/edit': {
      id: '/ingredients/$ingredientId/edit'
      path: '/edit'
      fullPath: '/ingredients/$ingredientId/edit'
      preLoaderRoute: typeof IngredientsIngredientIdEditImport
      parentRoute: typeof IngredientsIngredientIdImport
    }
    '/nutrients/$nutrientId/edit': {
      id: '/nutrients/$nutrientId/edit'
      path: '/edit'
      fullPath: '/nutrients/$nutrientId/edit'
      preLoaderRoute: typeof NutrientsNutrientIdEditImport
      parentRoute: typeof NutrientsNutrientIdImport
    }
    '/recipes/$recipeId/edit': {
      id: '/recipes/$recipeId/edit'
      path: '/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof RecipesRecipeIdEditImport
      parentRoute: typeof RecipesRecipeIdImport
    }
  }
}

// Create and export the route tree

interface FoodLogRouteChildren {
  FoodLoglayoutRoute: typeof FoodLoglayoutRoute
  FoodLogIndexRoute: typeof FoodLogIndexRoute
  FoodLogMealMealIdRoute: typeof FoodLogMealMealIdRoute
}

const FoodLogRouteChildren: FoodLogRouteChildren = {
  FoodLoglayoutRoute: FoodLoglayoutRoute,
  FoodLogIndexRoute: FoodLogIndexRoute,
  FoodLogMealMealIdRoute: FoodLogMealMealIdRoute,
}

const FoodLogRouteWithChildren =
  FoodLogRoute._addFileChildren(FoodLogRouteChildren)

interface IngredientsIngredientIdRouteChildren {
  IngredientsIngredientIdEditRoute: typeof IngredientsIngredientIdEditRoute
}

const IngredientsIngredientIdRouteChildren: IngredientsIngredientIdRouteChildren =
  {
    IngredientsIngredientIdEditRoute: IngredientsIngredientIdEditRoute,
  }

const IngredientsIngredientIdRouteWithChildren =
  IngredientsIngredientIdRoute._addFileChildren(
    IngredientsIngredientIdRouteChildren,
  )

interface IngredientsRouteChildren {
  IngredientslayoutRoute: typeof IngredientslayoutRoute
  IngredientsNewRoute: typeof IngredientsNewRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
}

const IngredientsRouteChildren: IngredientsRouteChildren = {
  IngredientslayoutRoute: IngredientslayoutRoute,
  IngredientsNewRoute: IngredientsNewRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
}

const IngredientsRouteWithChildren = IngredientsRoute._addFileChildren(
  IngredientsRouteChildren,
)

interface NutrientsNutrientIdRouteChildren {
  NutrientsNutrientIdEditRoute: typeof NutrientsNutrientIdEditRoute
}

const NutrientsNutrientIdRouteChildren: NutrientsNutrientIdRouteChildren = {
  NutrientsNutrientIdEditRoute: NutrientsNutrientIdEditRoute,
}

const NutrientsNutrientIdRouteWithChildren =
  NutrientsNutrientIdRoute._addFileChildren(NutrientsNutrientIdRouteChildren)

interface NutrientsRouteChildren {
  NutrientslayoutRoute: typeof NutrientslayoutRoute
  NutrientsNewRoute: typeof NutrientsNewRoute
  NutrientsIndexRoute: typeof NutrientsIndexRoute
}

const NutrientsRouteChildren: NutrientsRouteChildren = {
  NutrientslayoutRoute: NutrientslayoutRoute,
  NutrientsNewRoute: NutrientsNewRoute,
  NutrientsIndexRoute: NutrientsIndexRoute,
}

const NutrientsRouteWithChildren = NutrientsRoute._addFileChildren(
  NutrientsRouteChildren,
)

interface RecipesRecipeIdRouteChildren {
  RecipesRecipeIdEditRoute: typeof RecipesRecipeIdEditRoute
}

const RecipesRecipeIdRouteChildren: RecipesRecipeIdRouteChildren = {
  RecipesRecipeIdEditRoute: RecipesRecipeIdEditRoute,
}

const RecipesRecipeIdRouteWithChildren = RecipesRecipeIdRoute._addFileChildren(
  RecipesRecipeIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/food-log/$date': typeof FoodLogDateRoute
  '/food-log': typeof FoodLoglayoutRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRouteWithChildren
  '/ingredients': typeof IngredientslayoutRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/nutrients/$nutrientId': typeof NutrientsNutrientIdRouteWithChildren
  '/nutrients': typeof NutrientslayoutRoute
  '/nutrients/new': typeof NutrientsNewRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRouteWithChildren
  '/recipes/new-recipe': typeof RecipesNewRecipeRoute
  '/shopping-list/$itemId': typeof ShoppingListItemIdRoute
  '/shopping-list/new': typeof ShoppingListNewRoute
  '/consumption': typeof ConsumptionIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/food-log/': typeof FoodLogIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/nutrients/': typeof NutrientsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/shopping-list': typeof ShoppingListIndexRoute
  '/food-log/meal/$mealId': typeof FoodLogMealMealIdRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
  '/nutrients/$nutrientId/edit': typeof NutrientsNutrientIdEditRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/food-log/$date': typeof FoodLogDateRoute
  '/food-log': typeof FoodLogIndexRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRouteWithChildren
  '/ingredients': typeof IngredientsIndexRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/nutrients/$nutrientId': typeof NutrientsNutrientIdRouteWithChildren
  '/nutrients': typeof NutrientsIndexRoute
  '/nutrients/new': typeof NutrientsNewRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRouteWithChildren
  '/recipes/new-recipe': typeof RecipesNewRecipeRoute
  '/shopping-list/$itemId': typeof ShoppingListItemIdRoute
  '/shopping-list/new': typeof ShoppingListNewRoute
  '/consumption': typeof ConsumptionIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/shopping-list': typeof ShoppingListIndexRoute
  '/food-log/meal/$mealId': typeof FoodLogMealMealIdRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
  '/nutrients/$nutrientId/edit': typeof NutrientsNutrientIdEditRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/food-log/$date': typeof FoodLogDateRoute
  '/food-log': typeof FoodLogRouteWithChildren
  '/food-log/__layout': typeof FoodLoglayoutRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRouteWithChildren
  '/ingredients': typeof IngredientsRouteWithChildren
  '/ingredients/__layout': typeof IngredientslayoutRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/nutrients/$nutrientId': typeof NutrientsNutrientIdRouteWithChildren
  '/nutrients': typeof NutrientsRouteWithChildren
  '/nutrients/__layout': typeof NutrientslayoutRoute
  '/nutrients/new': typeof NutrientsNewRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRouteWithChildren
  '/recipes/new-recipe': typeof RecipesNewRecipeRoute
  '/shopping-list/$itemId': typeof ShoppingListItemIdRoute
  '/shopping-list/new': typeof ShoppingListNewRoute
  '/consumption/': typeof ConsumptionIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/food-log/': typeof FoodLogIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/nutrients/': typeof NutrientsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shopping-list/': typeof ShoppingListIndexRoute
  '/food-log/meal/$mealId': typeof FoodLogMealMealIdRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
  '/nutrients/$nutrientId/edit': typeof NutrientsNutrientIdEditRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/food-log/$date'
    | '/food-log'
    | '/ingredients/$ingredientId'
    | '/ingredients'
    | '/ingredients/new'
    | '/nutrients/$nutrientId'
    | '/nutrients'
    | '/nutrients/new'
    | '/recipes/$recipeId'
    | '/recipes/new-recipe'
    | '/shopping-list/$itemId'
    | '/shopping-list/new'
    | '/consumption'
    | '/dashboard'
    | '/food-log/'
    | '/ingredients/'
    | '/nutrients/'
    | '/recipes'
    | '/settings'
    | '/shopping-list'
    | '/food-log/meal/$mealId'
    | '/ingredients/$ingredientId/edit'
    | '/nutrients/$nutrientId/edit'
    | '/recipes/$recipeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/food-log/$date'
    | '/food-log'
    | '/ingredients/$ingredientId'
    | '/ingredients'
    | '/ingredients/new'
    | '/nutrients/$nutrientId'
    | '/nutrients'
    | '/nutrients/new'
    | '/recipes/$recipeId'
    | '/recipes/new-recipe'
    | '/shopping-list/$itemId'
    | '/shopping-list/new'
    | '/consumption'
    | '/dashboard'
    | '/recipes'
    | '/settings'
    | '/shopping-list'
    | '/food-log/meal/$mealId'
    | '/ingredients/$ingredientId/edit'
    | '/nutrients/$nutrientId/edit'
    | '/recipes/$recipeId/edit'
  id:
    | '__root__'
    | '/'
    | '/food-log/$date'
    | '/food-log'
    | '/food-log/__layout'
    | '/ingredients/$ingredientId'
    | '/ingredients'
    | '/ingredients/__layout'
    | '/ingredients/new'
    | '/nutrients/$nutrientId'
    | '/nutrients'
    | '/nutrients/__layout'
    | '/nutrients/new'
    | '/recipes/$recipeId'
    | '/recipes/new-recipe'
    | '/shopping-list/$itemId'
    | '/shopping-list/new'
    | '/consumption/'
    | '/dashboard/'
    | '/food-log/'
    | '/ingredients/'
    | '/nutrients/'
    | '/recipes/'
    | '/settings/'
    | '/shopping-list/'
    | '/food-log/meal/$mealId'
    | '/ingredients/$ingredientId/edit'
    | '/nutrients/$nutrientId/edit'
    | '/recipes/$recipeId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoodLogDateRoute: typeof FoodLogDateRoute
  FoodLogRoute: typeof FoodLogRouteWithChildren
  IngredientsIngredientIdRoute: typeof IngredientsIngredientIdRouteWithChildren
  IngredientsRoute: typeof IngredientsRouteWithChildren
  NutrientsNutrientIdRoute: typeof NutrientsNutrientIdRouteWithChildren
  NutrientsRoute: typeof NutrientsRouteWithChildren
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRouteWithChildren
  RecipesNewRecipeRoute: typeof RecipesNewRecipeRoute
  ShoppingListItemIdRoute: typeof ShoppingListItemIdRoute
  ShoppingListNewRoute: typeof ShoppingListNewRoute
  ConsumptionIndexRoute: typeof ConsumptionIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ShoppingListIndexRoute: typeof ShoppingListIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoodLogDateRoute: FoodLogDateRoute,
  FoodLogRoute: FoodLogRouteWithChildren,
  IngredientsIngredientIdRoute: IngredientsIngredientIdRouteWithChildren,
  IngredientsRoute: IngredientsRouteWithChildren,
  NutrientsNutrientIdRoute: NutrientsNutrientIdRouteWithChildren,
  NutrientsRoute: NutrientsRouteWithChildren,
  RecipesRecipeIdRoute: RecipesRecipeIdRouteWithChildren,
  RecipesNewRecipeRoute: RecipesNewRecipeRoute,
  ShoppingListItemIdRoute: ShoppingListItemIdRoute,
  ShoppingListNewRoute: ShoppingListNewRoute,
  ConsumptionIndexRoute: ConsumptionIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ShoppingListIndexRoute: ShoppingListIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/food-log/$date",
        "/food-log",
        "/ingredients/$ingredientId",
        "/ingredients",
        "/nutrients/$nutrientId",
        "/nutrients",
        "/recipes/$recipeId",
        "/recipes/new-recipe",
        "/shopping-list/$itemId",
        "/shopping-list/new",
        "/consumption/",
        "/dashboard/",
        "/recipes/",
        "/settings/",
        "/shopping-list/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/food-log/$date": {
      "filePath": "food-log/$date.tsx"
    },
    "/food-log": {
      "filePath": "food-log",
      "children": [
        "/food-log/__layout",
        "/food-log/",
        "/food-log/meal/$mealId"
      ]
    },
    "/food-log/__layout": {
      "filePath": "food-log/__layout.tsx",
      "parent": "/food-log"
    },
    "/ingredients/$ingredientId": {
      "filePath": "ingredients/$ingredientId.tsx",
      "children": [
        "/ingredients/$ingredientId/edit"
      ]
    },
    "/ingredients": {
      "filePath": "ingredients",
      "children": [
        "/ingredients/__layout",
        "/ingredients/new",
        "/ingredients/"
      ]
    },
    "/ingredients/__layout": {
      "filePath": "ingredients/__layout.tsx",
      "parent": "/ingredients"
    },
    "/ingredients/new": {
      "filePath": "ingredients/new.tsx",
      "parent": "/ingredients"
    },
    "/nutrients/$nutrientId": {
      "filePath": "nutrients/$nutrientId.tsx",
      "children": [
        "/nutrients/$nutrientId/edit"
      ]
    },
    "/nutrients": {
      "filePath": "nutrients",
      "children": [
        "/nutrients/__layout",
        "/nutrients/new",
        "/nutrients/"
      ]
    },
    "/nutrients/__layout": {
      "filePath": "nutrients/__layout.tsx",
      "parent": "/nutrients"
    },
    "/nutrients/new": {
      "filePath": "nutrients/new.tsx",
      "parent": "/nutrients"
    },
    "/recipes/$recipeId": {
      "filePath": "recipes/$recipeId.tsx",
      "children": [
        "/recipes/$recipeId/edit"
      ]
    },
    "/recipes/new-recipe": {
      "filePath": "recipes/new-recipe.tsx"
    },
    "/shopping-list/$itemId": {
      "filePath": "shopping-list/$itemId.tsx"
    },
    "/shopping-list/new": {
      "filePath": "shopping-list/new.tsx"
    },
    "/consumption/": {
      "filePath": "consumption/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/food-log/": {
      "filePath": "food-log/index.tsx",
      "parent": "/food-log"
    },
    "/ingredients/": {
      "filePath": "ingredients/index.tsx",
      "parent": "/ingredients"
    },
    "/nutrients/": {
      "filePath": "nutrients/index.tsx",
      "parent": "/nutrients"
    },
    "/recipes/": {
      "filePath": "recipes/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    },
    "/shopping-list/": {
      "filePath": "shopping-list/index.tsx"
    },
    "/food-log/meal/$mealId": {
      "filePath": "food-log/meal/$mealId.tsx",
      "parent": "/food-log"
    },
    "/ingredients/$ingredientId/edit": {
      "filePath": "ingredients/$ingredientId.edit.tsx",
      "parent": "/ingredients/$ingredientId"
    },
    "/nutrients/$nutrientId/edit": {
      "filePath": "nutrients/$nutrientId.edit.tsx",
      "parent": "/nutrients/$nutrientId"
    },
    "/recipes/$recipeId/edit": {
      "filePath": "recipes/$recipeId.edit.tsx",
      "parent": "/recipes/$recipeId"
    }
  }
}
ROUTE_MANIFEST_END */
